const ETHEREUM_BLOCKCHAIN_ID = 1;
const POLYGON_BLOCKCHAIN_ID = 137;
const ARBITRUM_BLOCKCHAIN_ID = 42161;

export {
    ETHEREUM_BLOCKCHAIN_ID,
    POLYGON_BLOCKCHAIN_ID,
    ARBITRUM_BLOCKCHAIN_ID,
};
